 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: rss-site-deploy
 spec:
   replicas: 2
   template:
     metadata:
       labels:
         app: web
     spec:
       containers:
         - name: front-end-dep
           image: nginx
           ports:
             - containerPort: 8086
         - name: rss-reader-dep
           image: nickchase/rss-php-nginx:v1
           ports:
             - containerPort: 8087
