version: "3.2"
services:
  registry:
    restart: always
    image: registry:2
    ports: 
      - 5007:5000
    volumes:
      - ./registro:/var/lib/registry
  web:
    restart: always
    image: konradkleine/docker-registry-frontend:v2
    ports: 
      - 8082:80
    environment:
      - ENV_DOCKER_REGISTRY_HOST=192.168.1.102 \
      - ENV_DOCKER_REGISTRY_PORT=5007
