version: "3.2"
services:
  web:
    image: nginx
    build: .
    depends_on:
      - redis
    ports:
      - 5005:5000
  redis:
    image: redis
  test:
      build:
        context: .
        dockerfile: Dockerfile.test
      depends_on:
        - web
      command: sh /test_dir/test.sh
